footer:
  dots:
  - link: https://www.facebook.com/solventie
  - link: https://www.instagram.com/solventie_/
  - link: https://www.linkedin.com/company/solventie/
  - link: https://g.page/r/CT7T0hQ29sriEB0
  boxes:
  - md: |
      - :none: [Autoconsumo Industrial](/autoconsumo-fotovoltaico/)
      - :none: [Bombeo Solar](/bombeo-solar/)
      - :none: [Ingeniería](/ingenieria/)
      - :none: [Eficiencia Energética](/eficiencia-energetica/)
  - md: |
      - :none: [Avisos Legales](/legal/ "[nofollow]")
      - :none: [Política de Privacidad](/privacidad/ "[nofollow]")
      - :none: [Política de Cookies](/cookies/ "[nofollow]")
      - :none: [Política de Calidad y Medio Ambiente](/politica-calidad-medio-ambiente/ "[nofollow]")
  - md: |
      - :none: [Apoyos](/apoyos/ "[nofollow]")
      - :none: [Contacto](/contacto/)
      - :none: [© Solvent](/)
      - :none: [Diseño web seacomoseo.com](https://seacomoseo.com/)
