name: Schedule Netlify Build

on:
  schedule:
    # Ejecuta todos los lunes a las 8:30 AM UTC.
    # ¡IMPORTANTE! Ajusta la hora a UTC. Si tu 8:30 AM local es diferente,
    # tendrás que calcular la hora UTC correspondiente.
    # Por ejemplo, si estás en Madrid (CEST = UTC+2) y quieres 8:30 AM CEST,
    # necesitas poner 6:30 AM UTC.
    # Formato Cron: Minuto Hora DíaDelMes Mes DíaDeLaSemana
    # '30 6 * * 1' significa: A los 30 minutos de la hora 6, cada día del mes, cada mes, cada lunes (1).
    # Recomendable usar "minutos raros" para evitar colisiones con otros cron jobs de github y minimizar la cola.
    - cron: '53 12 * * *' # <-- AJUSTA ESTA HORA A UTC

  # También puedes permitir ejecutarlo manualmente desde la pestaña Actions de GitHub
  workflow_dispatch:

jobs:
  trigger_netlify_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        # Usamos curl para enviar una solicitud POST vacía al build hook
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
